package com.yl.whs.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TEST.
 */
public class Test {

    private Long id;
    private String test;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Test() {
    }

    public Test(Long id) {
        this.id = id;
    }

    public Test(Long id, String test) {
        this.id = id;
        this.test = test;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
